development:
  adapter: async

test:
  adapter: async

production:
  adapter: postgresql
  url: postgres://ywoytnhoiubtxn:b126f7317b63e6571661a1ff900a1ab090f9f8b2f6807a61620d66fc428a778b@ec2-54-225-92-1.compute-1.amazonaws.com:5432/d43m414rcedf7e
  channel_prefix: bestbuy_production
